# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-04"

[[extensions]]
type = "ui_extension"
name = "checkout-ui"
handle = "checkout-ui"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview
#
#[[extensions.targeting]]
#module = "./src/Checkout.tsx"
#target = "purchase.checkout.block.render"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.shipping-option-list.render-after"

[[extensions.targeting]]
module = "./src/Phone.tsx"
target = "purchase.checkout.delivery-address.render-after"

[[extensions.targeting]]
module = "./src/TrustLogos.tsx"
target = "purchase.checkout.footer.render-after"

[[extensions.targeting]]
module = "./src/ProgressBar.tsx"
target = "purchase.checkout.block.render"
#
#[[extensions.targeting]]
#module = "./src/TrustBlock.tsx"
#target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true
network_access = true
block_progress = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
#network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "link_1"
type = "single_line_text_field"
name = "Logo url 1"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "link_2"
type = "single_line_text_field"
name = "Logo url 2"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "link_3"
type = "single_line_text_field"
name = "Logo url 3"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "link_4"
type = "single_line_text_field"
name = "Logo url 4"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "trust_href_1"
type = "single_line_text_field"
name = "Trust logo url 1"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "trust_href_2"
type = "single_line_text_field"
name = "Trust logo url 2"
description = "Enter url to your logo asset"
[[extensions.settings.fields]]
key = "trust_href_3"
type = "single_line_text_field"
name = "Trust logo url 3"
description = "Enter url to your logo asset"

