# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1115783b0f51ee3fe7c0b50d2bdbfe6"
name = "Poly & Bark Extensibility(PBE)"
application_url = "https://downloading-pete-rebate-php.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poly-bark-dev-plus.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_checkouts,write_checkouts,read_checkout_branding_settings,write_checkout_branding_settings,read_content,write_content,read_customer_merge,write_customer_merge,read_customers,write_customers,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,read_inventory,write_inventory,read_legal_policies,read_locales,write_locales,read_locations,read_markets,write_markets,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_marketing_events,write_marketing_events,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_payment_terms,write_payment_terms,read_price_rules,write_price_rules,read_products,write_products,read_product_listings,read_publications,write_publications,read_purchase_options,write_purchase_options,read_reports,write_reports,read_resource_feedbacks,write_resource_feedbacks,read_script_tags,write_script_tags,read_shipping,write_shipping,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_accounts,read_store_credit_account_transactions,write_store_credit_account_transactions,read_returns,write_returns,read_themes,write_themes,read_translations,write_translations,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_order_edits,write_order_edits,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://downloading-pete-rebate-php.trycloudflare.com/auth/callback",
  "https://downloading-pete-rebate-php.trycloudflare.com/auth/shopify/callback",
  "https://downloading-pete-rebate-php.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
